ITEM.name = "Dukes of the Nine Layers"
ITEM.desc = "A well kempt book that holds information on the Dukes of the Nine Layers."
ITEM.flag = "S"
ITEM.category = "Literature"
ITEM.uniqueID = "story_dukes"

ITEM.iconCam = {
	pos = Vector(0, 0, 200),
	ang = Angle(90, 0, 180),
	fov = 3.888,
}

ITEM.contents = [[
<p align="center"><font color='red' size='8'>Dukes of the Nine Layers</font></p><br/>
<font color='black' size='3'>
	1.Amdusias (also Amduscias, Amdukias or Ambduscias) has 29 legions of demons and spirits under his command. He is depicted as a human with claws instead of hands and feet, the head of a unicorn, and a trumpet to symbolize his powerful voice. Amdusias is associated with thunder and it has been said that his voice is heard during storms. In other sources, he is accompanied by the sound of trumpets when he comes and will give concerts if commanded, but while all his types of musical instruments can be heard they cannot be seen. He is regarded as being the demon in charge of the cacophonous music that is played in Hell. He can make trees bend at will.
<br/><br/>
	2.Agares (or Agreas), ruling the eastern zone of Hell, and being served by 31 legions of demons. He can make runaways come back and those who stand still run, finding pleasure in teaching immoral expressions. He also has the power to destroy dignities, both temporal and supernatural. He is depicted as a pale old man riding a crocodile.
<br/><br/>
	3.Valefar (or Malaphar, Malephar, Valafar, Valefor) is a Duke of Hell. He tempts people to steal and is in charge of a good relationship among thieves. Valefar is considered a good familiar by his associates "till they are caught in the trap." He commands ten legions of demons. He is represented as a lion with the head of a man, or as a lion with the head of a donkey.
<br/><br/>
	4.Barbatos is an Earl and Duke of Hell, ruling thirty legions of demons and has four kings as his companions to command his legions. He gives the understanding of the voices of the animals, says past and future, conciliates friends and rulers, and he can lead men to hidden treasures that have been hidden by the enchantment of magicians. His name seems to derive from Latin "barbatus", bearded, old man, philosopher. He is mentioned in The Lesser Key of Solomon.
<br/><br/>
	5.Gusion (also Gusoin, Gusoyn) is a strong Great Duke of Hell, and rules over forty legions of demons. He tells all past, present and future things, shows the meaning of all questions that are asked to him, reconciles friends, and gives honour and dignity. He is depicted as a baboon or according to some, in the form of a "xenophilus."
<br/><br/>
	6.Eligos (also Abigor or Eligor) is a Great Duke of Hell, ruling 60 legions of demons. He discovers hidden things and knows the future of wars and how soldiers should meet. He also attracts the favor of lords, knights and other important persons. He is depicted in the form of a goodly knight carrying a lance, an ensign and a sceptre (a serpent to Aleister Crowley). Alternatively he is depicted as a ghostly spectre, sometimes riding a semi-skeletal (sometimes winged) horse, or the Steed of Abigor. This is a minion of Hell itself, and was a gift from Beelzebub. It was created from the remains of one of the horses of the Garden of Eden.
<br/><br/>
	7.Zepar is a Great Duke of Hell. He commands 26 legions of inferior spirits. His office is to cause women to love men, and bring them together in love. He makes women barren. He is depicted with red clothes and armor, like a soldier.
<br/><br/>
	8.Bathin (or Bathym, Mathim, Marthim) is a Duke (Great Duke according to Pseudomonarchia Daemonum) of Hell, who has under his command thirty legions of demons. He knows the virtues of precious stones and herbs, and can bring men suddenly from one country to another. He helps one attain astral projection, and takes you wherever you want to go. He is depicted as a strong man with the tail of a serpent, riding a pale horse.
<br/><br/>
	9.Saleos (also Sallos and Zaleos) is a mighty Great Duke (a Great Earl to Johann Weyer) of Hell, ruling thirty legions of demons (Weyer does not mention anything concerning legions under his command). He is of a pacifist nature, and causes men to love women and women to love men (Weyer does not mention the nature of his work). He is depicted as a gallant and handsome soldier, wearing a ducal crown, and riding a crocodile.
<br/><br/>
	10.Aim (aka Aym or Haborym) is a Great Duke of Hell, very strong, and rules over twenty-six legions of demons. He sets cities, castles and great places on fire, makes men witty in all ways, and gives true answers concerning private matters. He is depicted as a man (handsome to some sources), but with three heads, one of a serpent, the second of a man, and the third of a cat to most authors, although some say of a calf, riding a viper, and carrying in his hand a lit firebrand with which he sets the requested things on fire.
<br/><br/>
	11.Buné is a Great Duke of Hell, mighty and strong, who has thirty legions of demons under his command. He changes the place of the dead and makes them demons that are under his power to gather together upon those sepulchres. Buné makes men eloquent and wise, and gives true answers to their demands and also richness. He speaks with a comely high voice. Buné is depicted as a three-headed dragon, being his heads like those of a dog, a griffin, and a man (although according to some grimoires he has two heads like a dragon and the third like a man).
<br/><br/>
	12.Berith (also Baal-berith) is a Great Duke of Hell, powerful and terrible, and has twenty-six legions of demons under his command. He tells things of the past, present and future with true answers; he can also turn all metals into gold, give dignities to men and confirm them. He speaks with a clear and subtle voice, and as recounted in Aleister Crowley's Illustrated Goetia, he is a liar when not answering questions. To speak with him the conjurer must wear a silver ring and put it before his face in the same form as it is needed in Beleth's case and demons do before Amaymon. He is depicted as a soldier wearing red clothes, a golden crown, and riding a red horse. Books on the subject tell that he is called according to whom invokes him, being called Berith by the Jews (see below). According to some demonologists from the 16th century, his power is stronger in June, meanwhile to Sebastien Michaelis he suggests murder and blasphemy and his adversary is St. Barnabas. His name was surely taken from Baal Berith (god), a form of Baal worshiped in Berith (Beirut), Phoenicia. In Alchemy Berith was the element with which all metals could be transmuted into gold. "Berith" is the Hebrew word for covenant, it was originated from the Akkadian (Babylonian) word "Biritu" which means "to fetter" or "to bond".
<br/><br/>
	13.Astaroth (also Ashtaroth, Astarot and Asteroth) is referred to in The Lesser Key of Solomon as a very powerful demon. In art, in the Dictionnaire Infernal, Astaroth is depicted as a nude man with feathered wings, wearing a crown, holding a serpent in one hand, and riding a beast with dragon-like wings and a serpent-like tail. According to Sebastien Michaelis he is a demon of the First Hierarchy, who seduces by means of laziness, vanity, and rationalized philosophies. His adversary is St. Bartholomew, who can protect against him for he has resisted Astaroth's temptations. To others, he teaches mathematical sciences and handicrafts, can make men invisible and lead them to hidden treasures, and answers every question formulated to him. He was also said to give to mortal beings the power over serpents. His name is possibly taken from the goddess Asherah or Astarte.
<br/><br/>
	14.Focalor (also Forcalor, Furcalor) is a powerful Great Duke of Hell, commanding three or thirty legions of spirits. Focalor is mentioned in The Lesser Key of Solomon as the forty-first of the 72 goetic demons. According to the grimoire: Focalor appears in the form of a man with a griffin's wings, kills men, drowns them, and overthrows warships; but if commanded by the conjurer he will not harm any man or thing. Focalor has power over wind and sea, and had hoped to return to heaven after one thousand years, but he was deceived in his hope. One of the three archdemons, Lucifuge Rofocale, has his second name as an anagram of Focalor, implying an intellectual relationship.
<br/><br/>
	15.Vepar (also Separ, Vephar) is a strong Great Duke of Hell, and rules twenty-nine legions of demons. He governs the waters and guides armoured ships laden with ammunition and weapons; he can also make, if requested, the sea rough and stormy, and to appear full of ships. Vepar can make men die in three days by putrefying sores and wounds, causing worms to breed in them, but if requested by the conjurer he can heal them immediately. Vepar is depicted as a mermaid.
<br/><br/>
	16.Vual (also Uvall, Voval, Vreal, Wal, Wall) is a mighty Great Duke of Hell, commanding thirty-seven legions of demons. He gives the love of women, causes friendship between friends and foes, and tells things past, present and to come. Vual is depicted as a dromedary that after a while changes shape into a man, and speaks the Egyptian language, but not perfectly, with a deep voice.
<br/><br/>
	17.Crocell (also called Crokel or Procell) is the 49th spirit of the Goetia, manifesting as an angel with a tendency to speak in dark and mysterious ways. Once a member of the Powers, he is now a Duke of Hell who rules over 48 legions of demons. When summoned by a conjuror, he can teach geometry and other liberal sciences. He can also warm bodies of water, create the illusion of the sound of rushing waters, and reveal the location of natural baths.
<br/><br/>
	18.Allocer (also Alocer, Alloces) is a demon whose title is Great Duke of Hell, and who has thirty-six legions of demons under his command. He induces people to immorality and teaches arts and all mysteries of the sky. He is described by Johann Weyer as appearing in the shape of a knight mounted on an enormous horse. His face has leonine characteristics; he has a ruddy complexion and burning eyes; and he speaks with much gravity. He is said to provide good familiars, and to teach astronomy and liberal arts. Allocer is often depicted riding a horse with dragon legs.
<br/><br/>
	19.(Duke/Count) Murmur (also Murmus, Murmuur, Murmux) is a Great Duke and Earl of Hell, and has thirty legions of demons under his command. He teaches Philosophy, and can oblige the souls of the deceased to appear before the conjurer to answer every desired question. Murmur is depicted as a soldier riding a Vulture or a Griffin, and wearing a ducal crown. Two of his ministers go before him making the sound of trumpets. "Murmur" in Latin means noise, whisper, murmur, and the sound of the trumpet.
<br/><br/>
	20.Gremory (aka Gamory, Gemory, or Gomory) is a strong Duke of Hell that governs twenty-six legions of demons. He tells all things past, present and future, about hidden treasures, and procures the love of women, young and old, but especially maidens. He is depicted as appearing in the form of a beautiful woman with the crown of a duchess tied around her waist, and riding a camel.
<br/><br/>
	21.Vapula (also Naphula) is a powerful Great Duke of Hell that commands thirty-six legions of demons. He teaches philosophy, mechanics, and sciences. Vapula is depicted as a griffin-winged lion.
<br/><br/>
	22.Flauros (also Flavros, Hauras, Haures, Havres) is a strong Great Duke of Hell, having thirty-six (twenty according to Pseudomonarchia Daemonum) legions of demons under his rule. He gives true answers of all things past, present and future, but he must be first commanded to enter a magic triangle for if not he will lie, deceive the conjurer, and beguile him in other business. But if he enters the triangle he will answer truly, and gladly speak about divinity, the creation of the world, himself, and other fallen angels. He can also destroy all the conjurer's enemies by burning them up. If the magician requests it, he will not suffer temptations from any spirit or in any form. Commonly people represent him as a humanoid leopard with big claws. Flauros is depicted as a terrible and strong leopard that under request of the conjurer changes into a man with fiery eyes and an awful expression. Flauros can also supposedly be called upon when a mortal wishes to take vengeance on other demons. This is likely included in his capability to destroy the conjurer's enemies.
<br/><br/>
	23.Dantalion (or Dantalian) is a powerful Great Duke of Hell, with thirty-six legions of demons under his command; he is the 71st of 72 spirits of Solomon. He teaches all arts and sciences, and also declares the secret counsel of anyone, given that he knows the thoughts of all people and can change them at his will. He can also cause love and show the similitude of any person, show the same by means of a vision, and let them be in any part of the world they will. He is depicted as a man with many appearances, which means the faces of all men and women. There are also many depictions in which he is said to hold a book in one of his hands:
		23a. "The Seventy-first Spirit is Dantalion. He is a Duke Great and Mighty, appearing in the Form of a Man with many Countenances, all Men's and Women's Faces; and he hath a Book in his right hand. His Office is to teach all Arts and Sciences unto any; and to declare the Secret Counsel of any one; for he knoweth the Thoughts of all Men and Women, and can change them at his Will. He can cause Love, and show the Similitude of any person, and show the same by a Vision, let them be in what part of the World they Will. He governeth 36 Legions of Spirits; and this is his Seal, which wear thou, etc." - The Lesser Key of Solomon


]]

