ITEM.name = "Marquises of the Forbidden Lands"
ITEM.desc = "A well kempt book that holds information on the Marquises of the Forbidden Lands."
ITEM.flag = "S"
ITEM.category = "Literature"
ITEM.uniqueID = "story_marquises"

ITEM.iconCam = {
	pos = Vector(0, 0, 200),
	ang = Angle(90, 0, 180),
	fov = 3.888,
}

ITEM.contents = [[
<p align="center"><font color='red' size='8'>Marquises of the Forbidden Lands</font></p><br/>
<font color='black' size='3'>
	1.Gamigin (also Gamygin, Gamigm or Samigina) is a Great Marquis of Hell who rules over thirty legions of demons. He teaches all liberal sciences and gives an account of the souls of those who died in sin and who drowned in the sea, speaking with a rough voice. He also answers what is asked about, and stays with the conjurer until he or she is satisfied. Gamigin is depicted as a little horse or a donkey, which changes form into a man under the conjurer's request.
<br/><br/>
	2.Aamon (or Amon, Nahum) is a Marquis of Hell who governs forty infernal legions. He appears as a wolf with a serpent's tail who can breathe fire, or as a man with a raven's head, sometimes depicted with canine teeth. He tells of all things past and future. He procures feuds, and reconciles controversies between friends and foes.
<br/><br/>
	3.Leraje (also Leraie, Leraikha, Leraye, Loray, Oray) is a mighty Great Marquis of Hell who has thirty legions of demons under his power. He causes great battles and disputes, and makes gangrene wounds caused by arrows. He is depicted as a gallant and handsome archer clad in green, carrying a bow and quiver.
<br/><br/>
	4.The demon Naberius (also Naberus, Nebiros and Cerberus, Cerbere) was first mentioned by Johann Weyer in 1583. He is supposedly the most valiant Marquis of Hell, and has nineteen legions of demons under his command. He makes men cunning in all arts, but especially in rhetoric, speaking with a hoarse voice. He also restores lost dignities and honors, although to Johann Weyer he procures the loss of them. Naberius appears as a three-headed dog or a raven. He has a raucous voice but presents himself as eloquent and amiable. He teaches the art of gracious living. He is depicted as a crow or a black crane. Concerning his name, it is unclear if there is an association with the Greek Cerberus. It is said that in 1583, Johann Weyer considers both of them to be the same demon. He claimed:
		4a."Naberius [Naberus], alias Cerberus, is a valiant marquesse, shewing himselfe in the forme of a crowe, when he speaketh with a hoarse voice: he maketh a man amiable and cunning in all arts, and speciallie in rhetorike, he procureth the losse of prelacies and dignities: nineteene legions heare (and obeie) him."
<br/><br/>
	5.(Marquis\Count) Ronové (also Ronove, Roneve, Ronwe) is a Marquis and Great Earl of Hell, commanding twenty legions of demons. He teaches Rhetoric, languages, and gives good and loyal servants and the favour of friends and foes. He is described as a monster holding a staff, without detailing his appearance. He is also described as taker of old souls; often coming to earth to harvest souls of decrepit humans and animals near death.
<br/><br/>
	6.Forneus is a Great Marquis of Hell, and has twenty-nine legions of demons under his rule. He teaches Rhetoric and languages, gives men a good name, and makes them be loved by their friends and foes. He is depicted as a great sea monster. His name seems to come from Latin "fornus", "furnus": "oven".
<br/><br/>
	7.Marchosias (also Marchocias) is a powerful Great Marquis of Hell, commanding thirty legions of demons. He is a strong and excellent fighter and very reliable to the conjurer, giving true answers to all questions. Marchosias hoped after one thousand and two hundred years to return to heaven with the non-fallen angels, but he is deceived in that hope. He is depicted as a wolf with a man's form as well as a griffin's wings and a serpent's tail, that under request changes shape into a man. The name Marchosias comes from Late Latin marchio, "marquis".
<br/><br/>
	8.Phenex (also Pheynix, Phoenix, Phoeniex) is a Great Marquis of Hell and has twenty legions of demons under his command. He teaches all wonderful sciences, is an excellent poet, and is very obedient to the conjuror. Phenex hopes to return to Heaven after 1,200 years, but he is deceived in this hope. He is depicted as a phoenix, which sings sweet notes with the voice of a child, but the conjurer must warn his companions (for he has not to be alone) not to hear them and ask him to put in human shape, which the demon supposedly does after a certain amount of time. Johann Weyer's Pseudomonarchia Daemonum describes this spirit as follows:
		8a."Phoenix is a great marquesse, appearing like the bird Phoenix, having a child's voice: but before he standeth still before the conjuror, he singeth manie sweet notes. Then the exorcist with his companions must beware he give no eare to the melodie, but must by and by bid him put on humane shape; then will he speake marvelous of all wonderfull sciences. He is an excellent poet, and obedient, he hopeth to returne to the seventh throne after a thousand two hundredth yeares, and governeth twentie legions."
<br/><br/>
	9.Sabnock (also spelled Sab Nac, Sabnac, Sabnach, Sabnack, Sabnacke, Salmac and Savnock) is a mighty Great Marquis of Hell, who has 50 legions of demons under his command. He builds high towers, castles and cities, furnishing them with weapons, ammunition, etc., gives good familiars, and can afflict men for several days making their wounds and sores gangrenous or filling them with worms. Sabnock is depicted as a soldier with armor and weapons, the head of a lion, and riding a pale horse.
<br/><br/>
	10.Shax (also spelled Chax, Shan, Shass, Shaz, and Scox) is a Great Marquis of Hell, and has power over 30 legions of demons on evil horses. He takes away the sight, hearing and understanding of any person under the conjurer's request, and steals money out of kings' houses, carrying it back to the people. He also steals horses and everything the conjurer asks. Shax can also discover hidden things if they are not kept by evil spirits, and sometimes gives good familiars, but sometimes those familiars deceive the conjurer. He should not be bothered too often. Shax is thought to be faithful and obedient, but is a great liar and will deceive the conjurer unless obliged to enter a magic triangle drawn on the floor. He will then speak marvellously and tell the truth. He knows when lies are told and uses these to teach lessons. He is depicted as a stork that speaks with a hoarse but subtle voice; his voice changes into a beautiful one once he enters the magic triangle.
<br/><br/>
	11.Orias (also spelled Oriax) is a Great Marquis of Hell, and has thirty legions of demons under his command. He knows and teaches the virtues of the stars and the mansions of the planets (the influence of each planet depending on the astrological sign in which it is in a specific moment and the influence of that sign on an individual depending on how the zodiac was configured at the moment of his/her birth or at the moment of asking a question to the astrologist); he also gives dignities, prelacies, and the favour of friends and foes, and can metamorphose a man into any shape.
<br/><br/>
	12.Andras is a Great Marquis of Hell, having under his command thirty legions of demons. He sows discord among people. According to the Goetia, Andras was a Grand Marquis of Hell, appearing with a winged angel's body and the head of an owl or raven, riding upon a strong black wolf and wielding a sharp and bright sword. He was also responsible for sowing discord, and commanded 30 infernal legions. He is the 63rd of the 72 spirits of Solomon. Andras was considered to be a highly dangerous demon, who could kill the conjuring magician and his assistants if precautions were not taken. The Dutch demonologist Johannes Wier, in his Pseudomonarchia Daemonum, says of Andras:
		12a."Andras is a great marquesse, and seemes in an angels shape with a head like a blacke night raven, riding upon a blacke and a verie strong woolfe, flourishing with a sharpe sword in his hand, he can kill the maister, the servant, and all assistants, he is author of discords, and ruleth thirtie legions."
		12b."Grand Marquis of Hell. He appears to have the body of an angel and the head of a wood owl, and to be riding a black wolf and carrying in his hand a pointed saber. He teaches those whom he favors to kill their enemies, masters and servants. He stirs up trouble and dissension. He commands thirty legions." - Collin de Plancy
<br/><br/>
	13.Andrealphus (also Androalphus) appears as the 54th demon in Johann Weyer's tome on demonology Pseudomonarchia Daemonum and is described as a great Marquis with the appearance of a Peacock who raises great noises and teaches cunning in astronomy, and when in human form also teaches geometry in a perfect manner. He is also described as ruling over thirty legions and as having the ability to turn any man into a bird. Andrealphus also appears as the 65th demon in the Goetia where he is described with similar traits, but also including the ability to make men subtle in all things pertaining to Mensuration, among other things.
<br/><br/>
	14.Kimaris (also known by the alternate names Cimeies, Cimejes and Cimeries) is most widely known as the 66th demon of the first part of the Lemegeton (popularly known as the Ars Goetia). He is described as a warrior riding a goodly black horse, and possesses the abilities of locating lost or hidden treasures, teaching trivium (grammar, logic and rhetoric) and making a man into a warrior of his own likeness. He holds the rank of marquis, and is served by 20 legions. He also rules over all the spirits of Africa. Much the same description is found in the earlier text of Johann Weyer's catalog of demons, Pseudomonarchia Daemonum (published 1563). Earlier still is the Munich Handbook of Necromancy: Clm 849 (published by Richard Kieckhefer, as Forbidden Rites: a necromancer's manual of the 15th century 1998) which lists an entity named Tuvries with much the same characteristics, except that he has 30 legions of servitors, and can cause a person to cross seas and rivers quickly. Most likely, Tuvries is a mistranscription of Cymries. Kimaris, as Cimeries, is also found on Anton LaVey's list of infernal names, although it is not known why LaVey chose Kimaris as one of the comparatively few Goetic daimons included. Aleister Crowley, in 777, gives Kimaris the Hebrew spelling KYMAVR and attributes him to the four of disks and the third decan of Capricorn by night. KYMAVR may allude to "Khem-our" (black light), a form of Horus mentioned in H. P. Blavatsky's Secret Doctrine. In Sepher Sephiroth, he is listed as KYTzAVR, with a gematria of 327, although KYMAVR=277. Since Tzaddi=90, which is also Mem spelled in full, the gematric substitution may be deliberate or a blind. In Harleian Ms. 6482, titled "The Rosie Crucian Secrets" (printed by the Aquarian Press, 1985), Dr. Rudd lists Cimeries as the 26th spirit made use of by King Solomon. He also attributes an angel Cimeriel to one of Dee's Enochian Ensigns of Creation, the tablet of 24 mansions (see McLean, Treatise on Angel Magic). The earliest mention of Chamariel is in Rossi's Gnostic tractate (see Meyer and Smith, Ancient Christian Magic). It is probable that the earliest mention of Kimaris is also Coptic, found in the London oriental mss 6796 where the name "Akathama Chamaris" appears (Meyer and Smith). In this text, the entity in question does not appear to be evil; rather, he is addressed as a godlike helping spirit. Baskin's Dictionary of Satanism speculates that Cimeries is derived from Cimmerians, a warlike people mentioned in the works of several classical authors as dwelling totally in darkness. It is also possible that Cimeries is derived from Chimaira, the three-headed, fire-breathing lion-goat-serpent who eventually became one of the guardians of the underworld. There is a precedent, considering that the harmless Phoenix is also demonized in the Goetia.
<br/><br/>
	15.Decarabia (also called Carabia) is a demon and, according to The Lesser Key of Solomon, a Great Marquis of Hell, or a King and Earl according to the original Latin version of the Pseudomonarchia Daemonum (these were somehow left out of the English translation by Reginald Scot). He has thirty legions of demons under his command. Decarabia knows the virtues of all herbs and precious stones, and can change into all birds and sing and fly like them before the conjurer. He is depicted as appearing as a pentagram star, changing into a man under the conjurer's request.
<br/><br/>


]]

